# Generated by Django 3.2.13 on 2022-12-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('U', 'User'), ('C', 'Critic')], max_length=1),
        ),
    ]
