# Generated by Django 3.2.13 on 2022-12-08 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='card_id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_id',
        ),
        migrations.AddField(
            model_name='benefit',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='card.card'),
        ),
    ]
