# Generated by Django 3.2.13 on 2022-12-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_in_out',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
