# Generated by Django 3.2.13 on 2022-12-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_detailcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcomment',
            name='rate',
            field=models.CharField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
