# Generated by Django 3.2.13 on 2022-12-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_detailcomment_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailcomment',
            old_name='post',
            new_name='card',
        ),
    ]
