# Generated by Django 3.2.13 on 2022-12-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_rename_post_detailcomment_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
