# Generated by Django 3.2.13 on 2022-12-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_detailcomment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailcomment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='detailcomment',
            name='updated_at',
        ),
    ]
