# Generated by Django 3.2.13 on 2022-12-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20221204_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
