# Generated by Django 3.2.13 on 2022-12-05 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_card_card_in_out'),
        ('card', '0007_detailcomment_updated_at'),
    ]

    operations = [
    ]
