# Generated by Django 3.2.13 on 2022-11-30 02:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Magezine',
            new_name='Magazine',
        ),
    ]
