# Generated by Django 3.2.13 on 2022-12-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_magazine_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='grade',
            field=models.CharField(choices=[('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], max_length=10),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='tag',
            field=models.CharField(choices=[('BASIC', '기초상식'), ('RECOMMEND', '추천·리뷰'), ('NEWS', '뉴스'), ('BODO', '보도자료'), ('YEAR', '연말정산'), ('ECT', '기타')], default='ECT', max_length=20, verbose_name='태그명'),
        ),
    ]
