# Generated by Django 3.2.13 on 2022-11-30 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazine', '0002_rename_magezine_magazine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.magazine')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
