# Generated by Django 3.2.13 on 2022-12-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_auto_20221205_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='tag',
            field=models.CharField(choices=[('RECOMMEND', '추천·리뷰'), ('NEWS', '뉴스'), ('BODO', '보도자료'), ('BASIC', '기초상식'), ('YEAR', '연말정산')], default=2, max_length=20, verbose_name='태그명'),
            preserve_default=False,
        ),
    ]
