# Generated by Django 3.2.13 on 2022-12-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_magazine_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='tag',
            field=models.CharField(choices=[('BASIC', '기초상식'), ('NEWS', '뉴스'), ('RECOMMEND', '추천·리뷰'), ('YEAR', '연말정산'), ('BODO', '보도자료')], max_length=20, verbose_name='태그명'),
        ),
    ]
