# Generated by Django 3.2.13 on 2022-11-30 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_alter_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='grade',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='magazine',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
