# Generated by Django 3.2.13 on 2022-12-09 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazine', '0007_alter_magazine_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='bookmark_users',
            field=models.ManyToManyField(related_name='bookmark_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='tag',
            field=models.CharField(choices=[('BASIC', '기초상식'), ('RECOMMEND', '추천·리뷰'), ('NEWS', '뉴스'), ('BODO', '보도자료'), ('ECT', '기타'), ('YEAR', '연말정산')], default='ECT', max_length=20, verbose_name='태그명'),
        ),
    ]
