# Generated by Django 3.2.13 on 2022-12-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0007_alter_magazine_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='tag',
            field=models.CharField(choices=[('ECT', '기타'), ('BODO', '보도자료'), ('NEWS', '뉴스'), ('YEAR', '연말정산'), ('RECOMMEND', '추천·리뷰'), ('BASIC', '기초상식')], default='ECT', max_length=20, verbose_name='태그명'),
        ),
    ]
