# Generated by Django 3.2.13 on 2022-12-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0008_auto_20221209_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='tag',
            field=models.CharField(choices=[('RECOMMEND', '추천·리뷰'), ('ECT', '기타'), ('YEAR', '연말정산'), ('BASIC', '기초상식'), ('BODO', '보도자료'), ('NEWS', '뉴스')], default='ECT', max_length=20, verbose_name='태그명'),
        ),
    ]
